// list of the course
export const ADMIN_ALL_COURSE_LIST_REQUEST = "ADMIN_ALL_COURSE_LIST_REQUEST";
export const ADMIN_ALL_COURSE_LIST_SUCCESS = "ADMIN_ALL_COURSE_LIST_SUCCESS";
export const ADMIN_ALL_COURSE_LIST_FAIL = "ADMIN_ALL_COURSE_LIST_FAIL";

// getting a specific course
export const GET_SINGLE_COURSE_REQUEST = "GET_SINGLE_COURSE_REQUEST";
export const GET_SINGLE_COURSE_SUCCESS = "GET_SINGLE_COURSE_SUCCESS";
export const GET_SINGLE_COURSE_FAIL = "GET_SINGLE_COURSE_FAIL";

export const GET_ALL_CATEGORIES_REQUEST = "GET_ALL_CATEGORIES_REQUEST";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";

export const CLEAR_COURSE_ERRORS = "CLEAR_COURSE_ERRORS";
