export const ADMIN_ALL_COURSE_LIST_REQUEST = "ADMIN_ALL_COURSE_LIST_REQUEST";
export const ADMIN_ALL_COURSE_LIST_SUCCESS = "ADMIN_ALL_COURSE_LIST_SUCCESS";
export const ADMIN_ALL_COURSE_LIST_FAIL = "ADMIN_ALL_COURSE_LIST_FAIL";

export const CLEAR_COURSE_ERRORS = "CLEAR_COURSE_ERRORS";
